[package]
name = "ab"
version = "0.1.0"
authors = ["Serge <sin8@hawaii.edu>"]
edition = "2018"

[build-dependencies]
protoc-rust = "1.4"

[dependencies]
serde_json = "1.0"
serde_derive = "*"
serde = "*"
zmq = "0.8"
regex = "1.1.6"
mongodb = "0.3"
lazy_static = "1.3.0"
protobuf="1.3"
