[package]
name = "triggering_v3"
version = "0.1.0"
authors = ["sin"]

[build-dependencies]
protoc-rust = "1.4"
serde_json = "1.0"

[dependencies]
protobuf="1.3"
serde_json = "*"
serde_derive = "*"
serde = "*"
zmq="*"
network-manager="*"
uptime_lib ="*"


[dependencies.pnet]
version = "0.21.0"
