// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opq.proto

#ifndef PROTOBUF_opq_2eproto__INCLUDED
#define PROTOBUF_opq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace opq {
namespace proto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_opq_2eproto();
void protobuf_AssignDesc_opq_2eproto();
void protobuf_ShutdownFile_opq_2eproto();

class Cycle;
class DataMessage;
class RequestDataMessage;
class RequestEventMessage;
class TriggerMessage;

enum RequestDataMessage_RequestType {
  RequestDataMessage_RequestType_PING = 1,
  RequestDataMessage_RequestType_PONG = 2,
  RequestDataMessage_RequestType_READ = 3,
  RequestDataMessage_RequestType_RESP = 4,
  RequestDataMessage_RequestType_ERROR = 5
};
bool RequestDataMessage_RequestType_IsValid(int value);
const RequestDataMessage_RequestType RequestDataMessage_RequestType_RequestType_MIN = RequestDataMessage_RequestType_PING;
const RequestDataMessage_RequestType RequestDataMessage_RequestType_RequestType_MAX = RequestDataMessage_RequestType_ERROR;
const int RequestDataMessage_RequestType_RequestType_ARRAYSIZE = RequestDataMessage_RequestType_RequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestDataMessage_RequestType_descriptor();
inline const ::std::string& RequestDataMessage_RequestType_Name(RequestDataMessage_RequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestDataMessage_RequestType_descriptor(), value);
}
inline bool RequestDataMessage_RequestType_Parse(
    const ::std::string& name, RequestDataMessage_RequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestDataMessage_RequestType>(
    RequestDataMessage_RequestType_descriptor(), name, value);
}
enum RequestEventMessage_TriggerType {
  RequestEventMessage_TriggerType_FREQUENCY_SAG = 1,
  RequestEventMessage_TriggerType_FREQUENCY_SWELL = 2,
  RequestEventMessage_TriggerType_VOLTAGE_SAG = 3,
  RequestEventMessage_TriggerType_VOLTAGE_SWELL = 4,
  RequestEventMessage_TriggerType_OTHER = 5
};
bool RequestEventMessage_TriggerType_IsValid(int value);
const RequestEventMessage_TriggerType RequestEventMessage_TriggerType_TriggerType_MIN = RequestEventMessage_TriggerType_FREQUENCY_SAG;
const RequestEventMessage_TriggerType RequestEventMessage_TriggerType_TriggerType_MAX = RequestEventMessage_TriggerType_OTHER;
const int RequestEventMessage_TriggerType_TriggerType_ARRAYSIZE = RequestEventMessage_TriggerType_TriggerType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestEventMessage_TriggerType_descriptor();
inline const ::std::string& RequestEventMessage_TriggerType_Name(RequestEventMessage_TriggerType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestEventMessage_TriggerType_descriptor(), value);
}
inline bool RequestEventMessage_TriggerType_Parse(
    const ::std::string& name, RequestEventMessage_TriggerType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestEventMessage_TriggerType>(
    RequestEventMessage_TriggerType_descriptor(), name, value);
}
// ===================================================================

class Cycle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opq.proto.Cycle) */ {
 public:
  Cycle();
  virtual ~Cycle();

  Cycle(const Cycle& from);

  inline Cycle& operator=(const Cycle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Cycle& default_instance();

  void Swap(Cycle* other);

  // implements Message ----------------------------------------------

  inline Cycle* New() const { return New(NULL); }

  Cycle* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Cycle& from);
  void MergeFrom(const Cycle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Cycle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // repeated int32 data = 2;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 2;
  ::google::protobuf::int32 data(int index) const;
  void set_data(int index, ::google::protobuf::int32 value);
  void add_data(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      data() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_data();

  // optional int32 last_gps = 3;
  bool has_last_gps() const;
  void clear_last_gps();
  static const int kLastGpsFieldNumber = 3;
  ::google::protobuf::int32 last_gps() const;
  void set_last_gps(::google::protobuf::int32 value);

  // optional int32 current_count = 4;
  bool has_current_count() const;
  void clear_current_count();
  static const int kCurrentCountFieldNumber = 4;
  ::google::protobuf::int32 current_count() const;
  void set_current_count(::google::protobuf::int32 value);

  // optional int32 flags = 5;
  bool has_flags() const;
  void clear_flags();
  static const int kFlagsFieldNumber = 5;
  ::google::protobuf::int32 flags() const;
  void set_flags(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:opq.proto.Cycle)
 private:
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_last_gps();
  inline void clear_has_last_gps();
  inline void set_has_current_count();
  inline void clear_has_current_count();
  inline void set_has_flags();
  inline void clear_has_flags();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > data_;
  ::google::protobuf::int32 last_gps_;
  ::google::protobuf::int32 current_count_;
  ::google::protobuf::int32 flags_;
  friend void  protobuf_AddDesc_opq_2eproto();
  friend void protobuf_AssignDesc_opq_2eproto();
  friend void protobuf_ShutdownFile_opq_2eproto();

  void InitAsDefaultInstance();
  static Cycle* default_instance_;
};
// -------------------------------------------------------------------

class DataMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opq.proto.DataMessage) */ {
 public:
  DataMessage();
  virtual ~DataMessage();

  DataMessage(const DataMessage& from);

  inline DataMessage& operator=(const DataMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DataMessage& default_instance();

  void Swap(DataMessage* other);

  // implements Message ----------------------------------------------

  inline DataMessage* New() const { return New(NULL); }

  DataMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DataMessage& from);
  void MergeFrom(const DataMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DataMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // repeated .opq.proto.Cycle cycles = 3;
  int cycles_size() const;
  void clear_cycles();
  static const int kCyclesFieldNumber = 3;
  const ::opq::proto::Cycle& cycles(int index) const;
  ::opq::proto::Cycle* mutable_cycles(int index);
  ::opq::proto::Cycle* add_cycles();
  ::google::protobuf::RepeatedPtrField< ::opq::proto::Cycle >*
      mutable_cycles();
  const ::google::protobuf::RepeatedPtrField< ::opq::proto::Cycle >&
      cycles() const;

  // @@protoc_insertion_point(class_scope:opq.proto.DataMessage)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::opq::proto::Cycle > cycles_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_opq_2eproto();
  friend void protobuf_AssignDesc_opq_2eproto();
  friend void protobuf_ShutdownFile_opq_2eproto();

  void InitAsDefaultInstance();
  static DataMessage* default_instance_;
};
// -------------------------------------------------------------------

class TriggerMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opq.proto.TriggerMessage) */ {
 public:
  TriggerMessage();
  virtual ~TriggerMessage();

  TriggerMessage(const TriggerMessage& from);

  inline TriggerMessage& operator=(const TriggerMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TriggerMessage& default_instance();

  void Swap(TriggerMessage* other);

  // implements Message ----------------------------------------------

  inline TriggerMessage* New() const { return New(NULL); }

  TriggerMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TriggerMessage& from);
  void MergeFrom(const TriggerMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TriggerMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // required uint64 time = 2;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // required float frequency = 3;
  bool has_frequency() const;
  void clear_frequency();
  static const int kFrequencyFieldNumber = 3;
  float frequency() const;
  void set_frequency(float value);

  // required float rms = 4;
  bool has_rms() const;
  void clear_rms();
  static const int kRmsFieldNumber = 4;
  float rms() const;
  void set_rms(float value);

  // optional float thd = 5;
  bool has_thd() const;
  void clear_thd();
  static const int kThdFieldNumber = 5;
  float thd() const;
  void set_thd(float value);

  // optional int32 last_gps = 6;
  bool has_last_gps() const;
  void clear_last_gps();
  static const int kLastGpsFieldNumber = 6;
  ::google::protobuf::int32 last_gps() const;
  void set_last_gps(::google::protobuf::int32 value);

  // optional int32 current_count = 7;
  bool has_current_count() const;
  void clear_current_count();
  static const int kCurrentCountFieldNumber = 7;
  ::google::protobuf::int32 current_count() const;
  void set_current_count(::google::protobuf::int32 value);

  // optional int32 flags = 8;
  bool has_flags() const;
  void clear_flags();
  static const int kFlagsFieldNumber = 8;
  ::google::protobuf::int32 flags() const;
  void set_flags(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:opq.proto.TriggerMessage)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_frequency();
  inline void clear_has_frequency();
  inline void set_has_rms();
  inline void clear_has_rms();
  inline void set_has_thd();
  inline void clear_has_thd();
  inline void set_has_last_gps();
  inline void clear_has_last_gps();
  inline void set_has_current_count();
  inline void clear_has_current_count();
  inline void set_has_flags();
  inline void clear_has_flags();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::int32 id_;
  float frequency_;
  float rms_;
  float thd_;
  ::google::protobuf::int32 last_gps_;
  ::google::protobuf::int32 current_count_;
  ::google::protobuf::int32 flags_;
  friend void  protobuf_AddDesc_opq_2eproto();
  friend void protobuf_AssignDesc_opq_2eproto();
  friend void protobuf_ShutdownFile_opq_2eproto();

  void InitAsDefaultInstance();
  static TriggerMessage* default_instance_;
};
// -------------------------------------------------------------------

class RequestDataMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opq.proto.RequestDataMessage) */ {
 public:
  RequestDataMessage();
  virtual ~RequestDataMessage();

  RequestDataMessage(const RequestDataMessage& from);

  inline RequestDataMessage& operator=(const RequestDataMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestDataMessage& default_instance();

  void Swap(RequestDataMessage* other);

  // implements Message ----------------------------------------------

  inline RequestDataMessage* New() const { return New(NULL); }

  RequestDataMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestDataMessage& from);
  void MergeFrom(const RequestDataMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestDataMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RequestDataMessage_RequestType RequestType;
  static const RequestType PING =
    RequestDataMessage_RequestType_PING;
  static const RequestType PONG =
    RequestDataMessage_RequestType_PONG;
  static const RequestType READ =
    RequestDataMessage_RequestType_READ;
  static const RequestType RESP =
    RequestDataMessage_RequestType_RESP;
  static const RequestType ERROR =
    RequestDataMessage_RequestType_ERROR;
  static inline bool RequestType_IsValid(int value) {
    return RequestDataMessage_RequestType_IsValid(value);
  }
  static const RequestType RequestType_MIN =
    RequestDataMessage_RequestType_RequestType_MIN;
  static const RequestType RequestType_MAX =
    RequestDataMessage_RequestType_RequestType_MAX;
  static const int RequestType_ARRAYSIZE =
    RequestDataMessage_RequestType_RequestType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  RequestType_descriptor() {
    return RequestDataMessage_RequestType_descriptor();
  }
  static inline const ::std::string& RequestType_Name(RequestType value) {
    return RequestDataMessage_RequestType_Name(value);
  }
  static inline bool RequestType_Parse(const ::std::string& name,
      RequestType* value) {
    return RequestDataMessage_RequestType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .opq.proto.RequestDataMessage.RequestType type = 1;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::opq::proto::RequestDataMessage_RequestType type() const;
  void set_type(::opq::proto::RequestDataMessage_RequestType value);

  // required uint32 sequence_number = 2;
  bool has_sequence_number() const;
  void clear_sequence_number();
  static const int kSequenceNumberFieldNumber = 2;
  ::google::protobuf::uint32 sequence_number() const;
  void set_sequence_number(::google::protobuf::uint32 value);

  // optional uint32 boxId = 3;
  bool has_boxid() const;
  void clear_boxid();
  static const int kBoxIdFieldNumber = 3;
  ::google::protobuf::uint32 boxid() const;
  void set_boxid(::google::protobuf::uint32 value);

  // optional uint64 time = 4;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 4;
  ::google::protobuf::uint64 time() const;
  void set_time(::google::protobuf::uint64 value);

  // optional uint64 back = 5;
  bool has_back() const;
  void clear_back();
  static const int kBackFieldNumber = 5;
  ::google::protobuf::uint64 back() const;
  void set_back(::google::protobuf::uint64 value);

  // optional uint64 forward = 6;
  bool has_forward() const;
  void clear_forward();
  static const int kForwardFieldNumber = 6;
  ::google::protobuf::uint64 forward() const;
  void set_forward(::google::protobuf::uint64 value);

  // optional uint32 num_cycles = 7;
  bool has_num_cycles() const;
  void clear_num_cycles();
  static const int kNumCyclesFieldNumber = 7;
  ::google::protobuf::uint32 num_cycles() const;
  void set_num_cycles(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:opq.proto.RequestDataMessage)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_sequence_number();
  inline void clear_has_sequence_number();
  inline void set_has_boxid();
  inline void clear_has_boxid();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_back();
  inline void clear_has_back();
  inline void set_has_forward();
  inline void clear_has_forward();
  inline void set_has_num_cycles();
  inline void clear_has_num_cycles();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  ::google::protobuf::uint32 sequence_number_;
  ::google::protobuf::uint64 time_;
  ::google::protobuf::uint64 back_;
  ::google::protobuf::uint32 boxid_;
  ::google::protobuf::uint32 num_cycles_;
  ::google::protobuf::uint64 forward_;
  friend void  protobuf_AddDesc_opq_2eproto();
  friend void protobuf_AssignDesc_opq_2eproto();
  friend void protobuf_ShutdownFile_opq_2eproto();

  void InitAsDefaultInstance();
  static RequestDataMessage* default_instance_;
};
// -------------------------------------------------------------------

class RequestEventMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:opq.proto.RequestEventMessage) */ {
 public:
  RequestEventMessage();
  virtual ~RequestEventMessage();

  RequestEventMessage(const RequestEventMessage& from);

  inline RequestEventMessage& operator=(const RequestEventMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestEventMessage& default_instance();

  void Swap(RequestEventMessage* other);

  // implements Message ----------------------------------------------

  inline RequestEventMessage* New() const { return New(NULL); }

  RequestEventMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestEventMessage& from);
  void MergeFrom(const RequestEventMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RequestEventMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef RequestEventMessage_TriggerType TriggerType;
  static const TriggerType FREQUENCY_SAG =
    RequestEventMessage_TriggerType_FREQUENCY_SAG;
  static const TriggerType FREQUENCY_SWELL =
    RequestEventMessage_TriggerType_FREQUENCY_SWELL;
  static const TriggerType VOLTAGE_SAG =
    RequestEventMessage_TriggerType_VOLTAGE_SAG;
  static const TriggerType VOLTAGE_SWELL =
    RequestEventMessage_TriggerType_VOLTAGE_SWELL;
  static const TriggerType OTHER =
    RequestEventMessage_TriggerType_OTHER;
  static inline bool TriggerType_IsValid(int value) {
    return RequestEventMessage_TriggerType_IsValid(value);
  }
  static const TriggerType TriggerType_MIN =
    RequestEventMessage_TriggerType_TriggerType_MIN;
  static const TriggerType TriggerType_MAX =
    RequestEventMessage_TriggerType_TriggerType_MAX;
  static const int TriggerType_ARRAYSIZE =
    RequestEventMessage_TriggerType_TriggerType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  TriggerType_descriptor() {
    return RequestEventMessage_TriggerType_descriptor();
  }
  static inline const ::std::string& TriggerType_Name(TriggerType value) {
    return RequestEventMessage_TriggerType_Name(value);
  }
  static inline bool TriggerType_Parse(const ::std::string& name,
      TriggerType* value) {
    return RequestEventMessage_TriggerType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint64 start_timestamp_ms_utc = 1;
  bool has_start_timestamp_ms_utc() const;
  void clear_start_timestamp_ms_utc();
  static const int kStartTimestampMsUtcFieldNumber = 1;
  ::google::protobuf::uint64 start_timestamp_ms_utc() const;
  void set_start_timestamp_ms_utc(::google::protobuf::uint64 value);

  // required uint64 end_timestamp_ms_utc = 2;
  bool has_end_timestamp_ms_utc() const;
  void clear_end_timestamp_ms_utc();
  static const int kEndTimestampMsUtcFieldNumber = 2;
  ::google::protobuf::uint64 end_timestamp_ms_utc() const;
  void set_end_timestamp_ms_utc(::google::protobuf::uint64 value);

  // required .opq.proto.RequestEventMessage.TriggerType trigger_type = 3;
  bool has_trigger_type() const;
  void clear_trigger_type();
  static const int kTriggerTypeFieldNumber = 3;
  ::opq::proto::RequestEventMessage_TriggerType trigger_type() const;
  void set_trigger_type(::opq::proto::RequestEventMessage_TriggerType value);

  // required double percent_magnitude = 4;
  bool has_percent_magnitude() const;
  void clear_percent_magnitude();
  static const int kPercentMagnitudeFieldNumber = 4;
  double percent_magnitude() const;
  void set_percent_magnitude(double value);

  // repeated int32 box_ids = 5;
  int box_ids_size() const;
  void clear_box_ids();
  static const int kBoxIdsFieldNumber = 5;
  ::google::protobuf::int32 box_ids(int index) const;
  void set_box_ids(int index, ::google::protobuf::int32 value);
  void add_box_ids(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      box_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_box_ids();

  // required string requestee = 6;
  bool has_requestee() const;
  void clear_requestee();
  static const int kRequesteeFieldNumber = 6;
  const ::std::string& requestee() const;
  void set_requestee(const ::std::string& value);
  void set_requestee(const char* value);
  void set_requestee(const char* value, size_t size);
  ::std::string* mutable_requestee();
  ::std::string* release_requestee();
  void set_allocated_requestee(::std::string* requestee);

  // required string description = 7;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 7;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // required bool request_data = 8;
  bool has_request_data() const;
  void clear_request_data();
  static const int kRequestDataFieldNumber = 8;
  bool request_data() const;
  void set_request_data(bool value);

  // @@protoc_insertion_point(class_scope:opq.proto.RequestEventMessage)
 private:
  inline void set_has_start_timestamp_ms_utc();
  inline void clear_has_start_timestamp_ms_utc();
  inline void set_has_end_timestamp_ms_utc();
  inline void clear_has_end_timestamp_ms_utc();
  inline void set_has_trigger_type();
  inline void clear_has_trigger_type();
  inline void set_has_percent_magnitude();
  inline void clear_has_percent_magnitude();
  inline void set_has_requestee();
  inline void clear_has_requestee();
  inline void set_has_description();
  inline void clear_has_description();
  inline void set_has_request_data();
  inline void clear_has_request_data();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 start_timestamp_ms_utc_;
  ::google::protobuf::uint64 end_timestamp_ms_utc_;
  double percent_magnitude_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > box_ids_;
  int trigger_type_;
  bool request_data_;
  ::google::protobuf::internal::ArenaStringPtr requestee_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  friend void  protobuf_AddDesc_opq_2eproto();
  friend void protobuf_AssignDesc_opq_2eproto();
  friend void protobuf_ShutdownFile_opq_2eproto();

  void InitAsDefaultInstance();
  static RequestEventMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Cycle

// required uint64 time = 1;
inline bool Cycle::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Cycle::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Cycle::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Cycle::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::uint64 Cycle::time() const {
  // @@protoc_insertion_point(field_get:opq.proto.Cycle.time)
  return time_;
}
inline void Cycle::set_time(::google::protobuf::uint64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.Cycle.time)
}

// repeated int32 data = 2;
inline int Cycle::data_size() const {
  return data_.size();
}
inline void Cycle::clear_data() {
  data_.Clear();
}
inline ::google::protobuf::int32 Cycle::data(int index) const {
  // @@protoc_insertion_point(field_get:opq.proto.Cycle.data)
  return data_.Get(index);
}
inline void Cycle::set_data(int index, ::google::protobuf::int32 value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:opq.proto.Cycle.data)
}
inline void Cycle::add_data(::google::protobuf::int32 value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:opq.proto.Cycle.data)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Cycle::data() const {
  // @@protoc_insertion_point(field_list:opq.proto.Cycle.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Cycle::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:opq.proto.Cycle.data)
  return &data_;
}

// optional int32 last_gps = 3;
inline bool Cycle::has_last_gps() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Cycle::set_has_last_gps() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Cycle::clear_has_last_gps() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Cycle::clear_last_gps() {
  last_gps_ = 0;
  clear_has_last_gps();
}
inline ::google::protobuf::int32 Cycle::last_gps() const {
  // @@protoc_insertion_point(field_get:opq.proto.Cycle.last_gps)
  return last_gps_;
}
inline void Cycle::set_last_gps(::google::protobuf::int32 value) {
  set_has_last_gps();
  last_gps_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.Cycle.last_gps)
}

// optional int32 current_count = 4;
inline bool Cycle::has_current_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Cycle::set_has_current_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Cycle::clear_has_current_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Cycle::clear_current_count() {
  current_count_ = 0;
  clear_has_current_count();
}
inline ::google::protobuf::int32 Cycle::current_count() const {
  // @@protoc_insertion_point(field_get:opq.proto.Cycle.current_count)
  return current_count_;
}
inline void Cycle::set_current_count(::google::protobuf::int32 value) {
  set_has_current_count();
  current_count_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.Cycle.current_count)
}

// optional int32 flags = 5;
inline bool Cycle::has_flags() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Cycle::set_has_flags() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Cycle::clear_has_flags() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Cycle::clear_flags() {
  flags_ = 0;
  clear_has_flags();
}
inline ::google::protobuf::int32 Cycle::flags() const {
  // @@protoc_insertion_point(field_get:opq.proto.Cycle.flags)
  return flags_;
}
inline void Cycle::set_flags(::google::protobuf::int32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.Cycle.flags)
}

// -------------------------------------------------------------------

// DataMessage

// required int32 id = 1;
inline bool DataMessage::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataMessage::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataMessage::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataMessage::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 DataMessage::id() const {
  // @@protoc_insertion_point(field_get:opq.proto.DataMessage.id)
  return id_;
}
inline void DataMessage::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.DataMessage.id)
}

// repeated .opq.proto.Cycle cycles = 3;
inline int DataMessage::cycles_size() const {
  return cycles_.size();
}
inline void DataMessage::clear_cycles() {
  cycles_.Clear();
}
inline const ::opq::proto::Cycle& DataMessage::cycles(int index) const {
  // @@protoc_insertion_point(field_get:opq.proto.DataMessage.cycles)
  return cycles_.Get(index);
}
inline ::opq::proto::Cycle* DataMessage::mutable_cycles(int index) {
  // @@protoc_insertion_point(field_mutable:opq.proto.DataMessage.cycles)
  return cycles_.Mutable(index);
}
inline ::opq::proto::Cycle* DataMessage::add_cycles() {
  // @@protoc_insertion_point(field_add:opq.proto.DataMessage.cycles)
  return cycles_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::opq::proto::Cycle >*
DataMessage::mutable_cycles() {
  // @@protoc_insertion_point(field_mutable_list:opq.proto.DataMessage.cycles)
  return &cycles_;
}
inline const ::google::protobuf::RepeatedPtrField< ::opq::proto::Cycle >&
DataMessage::cycles() const {
  // @@protoc_insertion_point(field_list:opq.proto.DataMessage.cycles)
  return cycles_;
}

// -------------------------------------------------------------------

// TriggerMessage

// required int32 id = 1;
inline bool TriggerMessage::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TriggerMessage::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TriggerMessage::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TriggerMessage::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 TriggerMessage::id() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.id)
  return id_;
}
inline void TriggerMessage::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.id)
}

// required uint64 time = 2;
inline bool TriggerMessage::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TriggerMessage::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TriggerMessage::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TriggerMessage::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::uint64 TriggerMessage::time() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.time)
  return time_;
}
inline void TriggerMessage::set_time(::google::protobuf::uint64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.time)
}

// required float frequency = 3;
inline bool TriggerMessage::has_frequency() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TriggerMessage::set_has_frequency() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TriggerMessage::clear_has_frequency() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TriggerMessage::clear_frequency() {
  frequency_ = 0;
  clear_has_frequency();
}
inline float TriggerMessage::frequency() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.frequency)
  return frequency_;
}
inline void TriggerMessage::set_frequency(float value) {
  set_has_frequency();
  frequency_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.frequency)
}

// required float rms = 4;
inline bool TriggerMessage::has_rms() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TriggerMessage::set_has_rms() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TriggerMessage::clear_has_rms() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TriggerMessage::clear_rms() {
  rms_ = 0;
  clear_has_rms();
}
inline float TriggerMessage::rms() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.rms)
  return rms_;
}
inline void TriggerMessage::set_rms(float value) {
  set_has_rms();
  rms_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.rms)
}

// optional float thd = 5;
inline bool TriggerMessage::has_thd() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void TriggerMessage::set_has_thd() {
  _has_bits_[0] |= 0x00000010u;
}
inline void TriggerMessage::clear_has_thd() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void TriggerMessage::clear_thd() {
  thd_ = 0;
  clear_has_thd();
}
inline float TriggerMessage::thd() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.thd)
  return thd_;
}
inline void TriggerMessage::set_thd(float value) {
  set_has_thd();
  thd_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.thd)
}

// optional int32 last_gps = 6;
inline bool TriggerMessage::has_last_gps() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void TriggerMessage::set_has_last_gps() {
  _has_bits_[0] |= 0x00000020u;
}
inline void TriggerMessage::clear_has_last_gps() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void TriggerMessage::clear_last_gps() {
  last_gps_ = 0;
  clear_has_last_gps();
}
inline ::google::protobuf::int32 TriggerMessage::last_gps() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.last_gps)
  return last_gps_;
}
inline void TriggerMessage::set_last_gps(::google::protobuf::int32 value) {
  set_has_last_gps();
  last_gps_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.last_gps)
}

// optional int32 current_count = 7;
inline bool TriggerMessage::has_current_count() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void TriggerMessage::set_has_current_count() {
  _has_bits_[0] |= 0x00000040u;
}
inline void TriggerMessage::clear_has_current_count() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void TriggerMessage::clear_current_count() {
  current_count_ = 0;
  clear_has_current_count();
}
inline ::google::protobuf::int32 TriggerMessage::current_count() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.current_count)
  return current_count_;
}
inline void TriggerMessage::set_current_count(::google::protobuf::int32 value) {
  set_has_current_count();
  current_count_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.current_count)
}

// optional int32 flags = 8;
inline bool TriggerMessage::has_flags() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void TriggerMessage::set_has_flags() {
  _has_bits_[0] |= 0x00000080u;
}
inline void TriggerMessage::clear_has_flags() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void TriggerMessage::clear_flags() {
  flags_ = 0;
  clear_has_flags();
}
inline ::google::protobuf::int32 TriggerMessage::flags() const {
  // @@protoc_insertion_point(field_get:opq.proto.TriggerMessage.flags)
  return flags_;
}
inline void TriggerMessage::set_flags(::google::protobuf::int32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.TriggerMessage.flags)
}

// -------------------------------------------------------------------

// RequestDataMessage

// required .opq.proto.RequestDataMessage.RequestType type = 1;
inline bool RequestDataMessage::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestDataMessage::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestDataMessage::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestDataMessage::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::opq::proto::RequestDataMessage_RequestType RequestDataMessage::type() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.type)
  return static_cast< ::opq::proto::RequestDataMessage_RequestType >(type_);
}
inline void RequestDataMessage::set_type(::opq::proto::RequestDataMessage_RequestType value) {
  assert(::opq::proto::RequestDataMessage_RequestType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.type)
}

// required uint32 sequence_number = 2;
inline bool RequestDataMessage::has_sequence_number() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestDataMessage::set_has_sequence_number() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestDataMessage::clear_has_sequence_number() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestDataMessage::clear_sequence_number() {
  sequence_number_ = 0u;
  clear_has_sequence_number();
}
inline ::google::protobuf::uint32 RequestDataMessage::sequence_number() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.sequence_number)
  return sequence_number_;
}
inline void RequestDataMessage::set_sequence_number(::google::protobuf::uint32 value) {
  set_has_sequence_number();
  sequence_number_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.sequence_number)
}

// optional uint32 boxId = 3;
inline bool RequestDataMessage::has_boxid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestDataMessage::set_has_boxid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestDataMessage::clear_has_boxid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestDataMessage::clear_boxid() {
  boxid_ = 0u;
  clear_has_boxid();
}
inline ::google::protobuf::uint32 RequestDataMessage::boxid() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.boxId)
  return boxid_;
}
inline void RequestDataMessage::set_boxid(::google::protobuf::uint32 value) {
  set_has_boxid();
  boxid_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.boxId)
}

// optional uint64 time = 4;
inline bool RequestDataMessage::has_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestDataMessage::set_has_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestDataMessage::clear_has_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestDataMessage::clear_time() {
  time_ = GOOGLE_ULONGLONG(0);
  clear_has_time();
}
inline ::google::protobuf::uint64 RequestDataMessage::time() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.time)
  return time_;
}
inline void RequestDataMessage::set_time(::google::protobuf::uint64 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.time)
}

// optional uint64 back = 5;
inline bool RequestDataMessage::has_back() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RequestDataMessage::set_has_back() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RequestDataMessage::clear_has_back() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RequestDataMessage::clear_back() {
  back_ = GOOGLE_ULONGLONG(0);
  clear_has_back();
}
inline ::google::protobuf::uint64 RequestDataMessage::back() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.back)
  return back_;
}
inline void RequestDataMessage::set_back(::google::protobuf::uint64 value) {
  set_has_back();
  back_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.back)
}

// optional uint64 forward = 6;
inline bool RequestDataMessage::has_forward() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RequestDataMessage::set_has_forward() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RequestDataMessage::clear_has_forward() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RequestDataMessage::clear_forward() {
  forward_ = GOOGLE_ULONGLONG(0);
  clear_has_forward();
}
inline ::google::protobuf::uint64 RequestDataMessage::forward() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.forward)
  return forward_;
}
inline void RequestDataMessage::set_forward(::google::protobuf::uint64 value) {
  set_has_forward();
  forward_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.forward)
}

// optional uint32 num_cycles = 7;
inline bool RequestDataMessage::has_num_cycles() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RequestDataMessage::set_has_num_cycles() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RequestDataMessage::clear_has_num_cycles() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RequestDataMessage::clear_num_cycles() {
  num_cycles_ = 0u;
  clear_has_num_cycles();
}
inline ::google::protobuf::uint32 RequestDataMessage::num_cycles() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestDataMessage.num_cycles)
  return num_cycles_;
}
inline void RequestDataMessage::set_num_cycles(::google::protobuf::uint32 value) {
  set_has_num_cycles();
  num_cycles_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestDataMessage.num_cycles)
}

// -------------------------------------------------------------------

// RequestEventMessage

// required uint64 start_timestamp_ms_utc = 1;
inline bool RequestEventMessage::has_start_timestamp_ms_utc() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestEventMessage::set_has_start_timestamp_ms_utc() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestEventMessage::clear_has_start_timestamp_ms_utc() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestEventMessage::clear_start_timestamp_ms_utc() {
  start_timestamp_ms_utc_ = GOOGLE_ULONGLONG(0);
  clear_has_start_timestamp_ms_utc();
}
inline ::google::protobuf::uint64 RequestEventMessage::start_timestamp_ms_utc() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.start_timestamp_ms_utc)
  return start_timestamp_ms_utc_;
}
inline void RequestEventMessage::set_start_timestamp_ms_utc(::google::protobuf::uint64 value) {
  set_has_start_timestamp_ms_utc();
  start_timestamp_ms_utc_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.start_timestamp_ms_utc)
}

// required uint64 end_timestamp_ms_utc = 2;
inline bool RequestEventMessage::has_end_timestamp_ms_utc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestEventMessage::set_has_end_timestamp_ms_utc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestEventMessage::clear_has_end_timestamp_ms_utc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestEventMessage::clear_end_timestamp_ms_utc() {
  end_timestamp_ms_utc_ = GOOGLE_ULONGLONG(0);
  clear_has_end_timestamp_ms_utc();
}
inline ::google::protobuf::uint64 RequestEventMessage::end_timestamp_ms_utc() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.end_timestamp_ms_utc)
  return end_timestamp_ms_utc_;
}
inline void RequestEventMessage::set_end_timestamp_ms_utc(::google::protobuf::uint64 value) {
  set_has_end_timestamp_ms_utc();
  end_timestamp_ms_utc_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.end_timestamp_ms_utc)
}

// required .opq.proto.RequestEventMessage.TriggerType trigger_type = 3;
inline bool RequestEventMessage::has_trigger_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestEventMessage::set_has_trigger_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestEventMessage::clear_has_trigger_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestEventMessage::clear_trigger_type() {
  trigger_type_ = 1;
  clear_has_trigger_type();
}
inline ::opq::proto::RequestEventMessage_TriggerType RequestEventMessage::trigger_type() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.trigger_type)
  return static_cast< ::opq::proto::RequestEventMessage_TriggerType >(trigger_type_);
}
inline void RequestEventMessage::set_trigger_type(::opq::proto::RequestEventMessage_TriggerType value) {
  assert(::opq::proto::RequestEventMessage_TriggerType_IsValid(value));
  set_has_trigger_type();
  trigger_type_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.trigger_type)
}

// required double percent_magnitude = 4;
inline bool RequestEventMessage::has_percent_magnitude() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestEventMessage::set_has_percent_magnitude() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestEventMessage::clear_has_percent_magnitude() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestEventMessage::clear_percent_magnitude() {
  percent_magnitude_ = 0;
  clear_has_percent_magnitude();
}
inline double RequestEventMessage::percent_magnitude() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.percent_magnitude)
  return percent_magnitude_;
}
inline void RequestEventMessage::set_percent_magnitude(double value) {
  set_has_percent_magnitude();
  percent_magnitude_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.percent_magnitude)
}

// repeated int32 box_ids = 5;
inline int RequestEventMessage::box_ids_size() const {
  return box_ids_.size();
}
inline void RequestEventMessage::clear_box_ids() {
  box_ids_.Clear();
}
inline ::google::protobuf::int32 RequestEventMessage::box_ids(int index) const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.box_ids)
  return box_ids_.Get(index);
}
inline void RequestEventMessage::set_box_ids(int index, ::google::protobuf::int32 value) {
  box_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.box_ids)
}
inline void RequestEventMessage::add_box_ids(::google::protobuf::int32 value) {
  box_ids_.Add(value);
  // @@protoc_insertion_point(field_add:opq.proto.RequestEventMessage.box_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RequestEventMessage::box_ids() const {
  // @@protoc_insertion_point(field_list:opq.proto.RequestEventMessage.box_ids)
  return box_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RequestEventMessage::mutable_box_ids() {
  // @@protoc_insertion_point(field_mutable_list:opq.proto.RequestEventMessage.box_ids)
  return &box_ids_;
}

// required string requestee = 6;
inline bool RequestEventMessage::has_requestee() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RequestEventMessage::set_has_requestee() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RequestEventMessage::clear_has_requestee() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RequestEventMessage::clear_requestee() {
  requestee_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_requestee();
}
inline const ::std::string& RequestEventMessage::requestee() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.requestee)
  return requestee_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestEventMessage::set_requestee(const ::std::string& value) {
  set_has_requestee();
  requestee_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.requestee)
}
inline void RequestEventMessage::set_requestee(const char* value) {
  set_has_requestee();
  requestee_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:opq.proto.RequestEventMessage.requestee)
}
inline void RequestEventMessage::set_requestee(const char* value, size_t size) {
  set_has_requestee();
  requestee_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:opq.proto.RequestEventMessage.requestee)
}
inline ::std::string* RequestEventMessage::mutable_requestee() {
  set_has_requestee();
  // @@protoc_insertion_point(field_mutable:opq.proto.RequestEventMessage.requestee)
  return requestee_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestEventMessage::release_requestee() {
  // @@protoc_insertion_point(field_release:opq.proto.RequestEventMessage.requestee)
  clear_has_requestee();
  return requestee_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestEventMessage::set_allocated_requestee(::std::string* requestee) {
  if (requestee != NULL) {
    set_has_requestee();
  } else {
    clear_has_requestee();
  }
  requestee_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), requestee);
  // @@protoc_insertion_point(field_set_allocated:opq.proto.RequestEventMessage.requestee)
}

// required string description = 7;
inline bool RequestEventMessage::has_description() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RequestEventMessage::set_has_description() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RequestEventMessage::clear_has_description() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RequestEventMessage::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_description();
}
inline const ::std::string& RequestEventMessage::description() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.description)
  return description_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestEventMessage::set_description(const ::std::string& value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.description)
}
inline void RequestEventMessage::set_description(const char* value) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:opq.proto.RequestEventMessage.description)
}
inline void RequestEventMessage::set_description(const char* value, size_t size) {
  set_has_description();
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:opq.proto.RequestEventMessage.description)
}
inline ::std::string* RequestEventMessage::mutable_description() {
  set_has_description();
  // @@protoc_insertion_point(field_mutable:opq.proto.RequestEventMessage.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RequestEventMessage::release_description() {
  // @@protoc_insertion_point(field_release:opq.proto.RequestEventMessage.description)
  clear_has_description();
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RequestEventMessage::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    set_has_description();
  } else {
    clear_has_description();
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:opq.proto.RequestEventMessage.description)
}

// required bool request_data = 8;
inline bool RequestEventMessage::has_request_data() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RequestEventMessage::set_has_request_data() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RequestEventMessage::clear_has_request_data() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RequestEventMessage::clear_request_data() {
  request_data_ = false;
  clear_has_request_data();
}
inline bool RequestEventMessage::request_data() const {
  // @@protoc_insertion_point(field_get:opq.proto.RequestEventMessage.request_data)
  return request_data_;
}
inline void RequestEventMessage::set_request_data(bool value) {
  set_has_request_data();
  request_data_ = value;
  // @@protoc_insertion_point(field_set:opq.proto.RequestEventMessage.request_data)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace opq

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::opq::proto::RequestDataMessage_RequestType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opq::proto::RequestDataMessage_RequestType>() {
  return ::opq::proto::RequestDataMessage_RequestType_descriptor();
}
template <> struct is_proto_enum< ::opq::proto::RequestEventMessage_TriggerType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opq::proto::RequestEventMessage_TriggerType>() {
  return ::opq::proto::RequestEventMessage_TriggerType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_opq_2eproto__INCLUDED
