version: '3.7'

services:
  view:
    image: ${VIEW_IMAGE}
    network_mode: "host"
    restart: always
    environment:
      - MONGO_URL
      - ROOT_URL
      - PORT
      - METEOR_SETTINGS
  mauka:
    image: ${MAUKA_IMAGE}
    restart: always
    network_mode: "host"
  health:
    image: ${HEALTH_IMAGE}
    restart: always
    network_mode: "host"
    volumes:
      - /tmp/opqhealth:/var/log/health