version: '3.7'

services:
  view:
    image: openpowerquality/opqview:0.1
    network_mode: "host"
    restart: always
    environment:
      - MONGO_URL
      - ROOT_URL
      - PORT
      - METEOR_SETTINGS
  mauka:
    image: openpowerquality/opqmauka:0.1
    restart: always
    network_mode: "host"
  health:
    image: openpowerquality/opqhealth:0.1
    restart: always
    network_mode: "host"
    volumes:
      - /tmp/opqhealth:/var/log/health