version: '3.7'

services:
  mongo:
    image: ${MONGO_IMAGE}
    restart: always
    expose:
      - "${MONGO_PORT}"
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "${MONGO_VOLUME}:/data/db"
  view:
    image: ${VIEW_IMAGE}
    depends_on:
      - mongo
    restart: always
    ports:
      - "127.0.0.1:${VIEW_PORT}:${VIEW_PORT}"
    environment:
      - MONGO_URL=${VIEW_MONGO_URL}
      - ROOT_URL=${VIEW_ROOT_URL}
      - PORT=${VIEW_PORT}
      - METEOR_SETTINGS
  mauka:
    image: ${MAUKA_IMAGE}
    depends_on:
      - mongo
    restart: always
    network_mode: "host"
  health:
    image: ${HEALTH_IMAGE}
    depends_on:
      - mongo
    restart: always
    network_mode: "host"
    volumes:
      - /tmp/opqhealth:/var/log/health
  boxupdateserver:
    image: ${BOXUPDATESERVER_IMAGE}
    restart: always
    network_mode: "host"
    expose:
      - "${BOXUPDATESERVER_HTTP_SERVER_PORT}"
    ports:
      - "${BOXUPDATESERVER_HTTP_SERVER_PORT}:${BOXUPDATESERVER_HTTP_SERVER_PORT}"
    command: ["${BOXUPDATESERVER_HTTP_SERVER_PORT}", "${BOXUPDATESERVER_UPDATES_DIR}"]
    volumes:
      - "${BOXUPDATESERVER_UPDATES_DIR}:${BOXUPDATESERVER_UPDATES_DIR}:ro"
