import { BoxEvents } from '../../api/box-events/BoxEventsCollection';
import { BoxOwners } from '../../api/users/BoxOwnersCollection';
import { Events } from '../../api/events/EventsCollection';
import { Healths } from '../../api/health/HealthsCollection';
import { LahaConfig } from '../../api/laha-config/LahaConfigCollection';
import { Locations } from '../../api/locations/LocationsCollection';
import { MakaiConfig } from '../../api/makai-config/MakaiConfigCollection';
import { Trends } from '../../api/trends/TrendsCollection.js';
import { SystemStats } from '../../api/system-stats/SystemStatsCollection.js';
import { OpqBoxes } from '../../api/opq-boxes/OpqBoxesCollection';
import { Regions } from '../../api/regions/RegionsCollection';
import { Measurements } from '../../api/measurements/MeasurementsCollection';
import { UserProfiles } from '../../api/users/UserProfilesCollection';
import { Notifications } from '../../api/notifications/NotificationsCollection';

BoxEvents.publish();
BoxOwners.publish();
Events.publish();
Healths.publish();
LahaConfig.publish();
Locations.publish();
MakaiConfig.publish();
Measurements.publish();
OpqBoxes.publish();
Regions.publish();
SystemStats.publish();
Trends.publish();
UserProfiles.publish();
Notifications.publish();
